title: "Project Lacewing"
description: "A European, open, community-driven answer to AI-driven vulnerability research. By DIVD."
baseurl: "/"
url: "https://divd-nl.github.io"

livereload: true

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - docs/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .github/

collections:
  partners:
    output: true
    permalink: /partner/:name/
  projects:
    output: true
    permalink: /projects/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "partners"
    values:
      layout: "partner"

twitter:
  username: DIVDnl

lacewing:
  contact_email: "lacewing@divd.nl"
  github_url: "https://github.com/DIVD-NL/web-lacewing"
  donate_url: "https://divd.nl/donate"
